"""
Django settings for inventory_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
import dj_database_url # type: ignore # Database configuration ke liye upar import kiya

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# -----------------------------------------------------------

# 1. SECURITY & HOSTS (PRODUCTION FIXES)
# ------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-)gqd&-#2)00$4*uqtd@wrb8zy=g11h(=7enxztus-6slxulb%%')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == 'True' 

# Production hosting domain aur local hosts yahan honge.
ALLOWED_HOSTS = os.environ.get('https://smartvyapar.netlify.app/', '127.0.0.1,localhost').split(',')


# Application definition
# ----------------------

INSTALLED_APPS = [
    # Django Built-ins
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party Apps
    'rest_framework', 
    'corsheaders', 
    'rest_framework_simplejwt', 
    
    # Local Apps
    'inventory_app',  
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # WhiteNoise Middleware (Static file serving ke liye)
    "whitenoise.middleware.WhiteNoiseMiddleware", 
]

ROOT_URLCONF = 'inventory_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory_backend.wsgi.application'


# 3. DATABASE (PRODUCTION FIX)
# ----------------------------

DATABASES = {
    'default': dj_database_url.config(
        # Koyeb ya anya hosting platform se DATABASE_URL environment variable padhega.
        default=os.environ.get('DATABASE_URL', f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
        conn_max_age=600 
    )
}


# Password validation
# -------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# --------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# 4. STATIC FILES (PRODUCTION FIX)
# --------------------------------
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'

# Frontend files ko static directory mein include karne ke liye.
STATICFILES_DIRS = [
    BASE_DIR / "frontend", 
]

# WhiteNoise storage backend use karein.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Other Settings
# --------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOW_ALL_ORIGINS = True # Sabhi URLs se connection allowed

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

CORS_ALLOW_ALL_ORIGINS = True